#!/bin/sh -e

PATH="/sbin:/bin"
RUN_DIR="/run/network"
IFSTATE="$RUN_DIR/ifstate"

[ -x /sbin/ifup ] || exit 0
[ -x /sbin/ifdown ] || exit 0

. /lib/lsb/init-functions

CONFIGURE_INTERFACES=yes
EXCLUDE_INTERFACES=

process_options() {
  [ -e /etc/network/options ] || return 0
  echo "/etc/network/options still exists and it will be IGNORED! Please use /etc/sysctl.conf instead."
}

check_ifstate() {
  if [ ! -d "$RUN_DIR" ] ; then
    if ! mkdir -p "$RUN_DIR" ; then
        echo "can't create $RUN_DIR"
        exit 1
    fi
  fi
  if [ ! -r "$IFSTATE" ] ; then
    if ! :> "$IFSTATE" ; then
        echo "can't initialise $IFSTATE"
        exit 1
    fi
  fi
}

ifup_hotplug () {
  if [ -d /sys/class/net ]
  then
    ifaces=$(for iface in $(ifquery --list --allow=hotplug); do
      link=${iface##:*}
      link=${link##.*}
      if [ -e "/sys/class/net/$link" ] && [ "$(cat /sys/class/net/$link/operstate)" = up ]
      then
        echo "$iface"
      fi
    done)
    if [ -n "$ifaces" ]
    then
      ifup $ifaces "$@" || true
    fi
  fi
}

process_exclusions() {
  set -- $EXCLUDE_INTERFACES
  exclusions=""
  for d
  do
    exclusions="-X $d $exclusions"
  done
  echo $exclusions
}

process_options
check_ifstate

if [ "$CONFIGURE_INTERFACES" = no ]
then
  echo "Not configuring network interfaces, see /etc/default/networking"
  exit 0
fi

set -f
exclusions=$(process_exclusions)
echo "[networking]: Configuring network interfaces"

if ifup -a $exclusions && ifup_hotplug $exclusions; then
  echo $?
else
  log_action_end_msg $?
fi

exec sleep infinity