#!/bin/bash

sv stop mountd || exit 1

. /etc/sv/nfs-kernel-server/common

echo "Unexporting directories for $DESC..."
$PREFIX/sbin/exportfs -au

RET=$?
if [ $RET != 0 ]; then
	echo $RET
	exit $RET
fi

if mountpoint -q $PROCNFSD_MOUNTPOINT; then
  $PREFIX/sbin/exportfs -f
fi