#!/bin/sh -e

supported_kernel() {
  case "$(uname -r)" in
    2.[012345].*|2.6.[0-9]|2.6.[0-9][!0-9]*) return 1 ;;
    2.6.[12][0-9]|2.6.[12][0-9][!0-9]*) return 1 ;;
    2.6.3[0-1]|2.6.3[0-1][!0-9]*) return 1 ;;
  esac
  return 0
}

# If the initramfs does not have /run, the initramfs udev database must
# be migrated from /dev/.udev/ to /run/udev/.
move_udev_database() {
  [ -e "$udev_root/.udev/" ] || return 0
  [ ! -e /run/udev/ ] || return 0
  [ -e /run/ ] || return 0
  mountpoint -q /run/ || return 0

  mv $udev_root/.udev/ /run/udev/ || true
}

# we need to unmount /dev/pts/ and remount it later over the tmpfs
unmount_devpts() {
  if mountpoint -q /dev/pts/; then
    umount -n -l /dev/pts/
  fi

  if mountpoint -q /dev/shm/; then
    umount -n -l /dev/shm/
  fi
}

# mount a tmpfs over /dev, if somebody did not already do it
mount_tmpfs() {
  if grep -E -q "^[^[:space:]]+ /dev (dev)?tmpfs" /proc/mounts; then
    mount -n -o remount,${dev_mount_options} -t tmpfs tmpfs /dev
    return
  fi

  if ! mount -n -o $dev_mount_options -t tmpfs tmpfs /dev; then
    echo "udev requires tmpfs support, not started"
    exit 1
  fi

  return 0
}

create_dev_makedev() {
  if [ -e /sbin/MAKEDEV ]; then
    ln -sf /sbin/MAKEDEV /dev/MAKEDEV
  else
    ln -sf /bin/true /dev/MAKEDEV
  fi
}

[ -x /sbin/udevd ] || exit 0

PATH="/sbin:/bin"

# defaults
tmpfs_size="10M"
udev_root="/dev"

if [ -e /etc/udev/udev.conf ]; then
  . /etc/udev/udev.conf
fi

. /lib/lsb/init-functions

if ! supported_kernel; then
  echo "udev requires a kernel >= 2.6.32, not started"
  exit 1
fi

if [ ! -e /proc/filesystems ]; then
  echo "udev requires a mounted procfs, not started"
  exit 1
fi

if ! grep -q '[[:space:]]tmpfs$' /proc/filesystems; then
  echo "udev requires tmpfs support, not started"
  exit 1
fi

if [ ! -d /sys/class/ ]; then
  echo "udev requires a mounted sysfs, not started"
  exit 1
fi

if [ ! -e /sys/kernel/uevent_helper ]; then
  echo "udev requires hotplug support, not started"
  exit 1
fi

if [ -d /sys/class/mem/null -a ! -L /sys/class/mem/null ] || \
   [ -e /sys/block -a ! -e /sys/class/block ]; then
  echo "CONFIG_SYSFS_DEPRECATED must not be selected"
  echo "Booting will continue in 30 seconds but many things will be broken"
  sleep 30
fi

##############################################################################

udev_root=${udev_root%/}

dev_mount_options='mode=0755'
if [ "$tmpfs_size" ]; then
  dev_mount_options="size=${tmpfs_size},${dev_mount_options}"
fi

if mountpoint -q $udev_root/; then
  TMPFS_MOUNTED=1
elif [ -e "$udev_root/.udev/" ]; then
  echo ".udev/ already exists on the static $udev_root"
fi

echo > /sys/kernel/uevent_helper
move_udev_database

if [ -z "$TMPFS_MOUNTED" ]; then
  unmount_devpts
  mount_tmpfs
  [ -d /proc/1 ] || mount -n /proc
fi

# clean up parts of the database created by the initramfs udev
udevadm info --cleanup-db

# set the SELinux context for devices created in the initramfs
[ -x /sbin/restorecon ] && /sbin/restorecon -R /dev

# /dev/null must be created before udevd is started
/lib/udev/create_static_nodes || true

echo "udevd: Starting the hotplug events dispatcher"
exec /sbin/udevd &

/lib/udev/write_dev_root_rule

echo "Synthesizing the initial hotplug events"
udevadm trigger --action=add
create_dev_makedev

# wait for the udevd childs to finish
echo "Waiting for /dev to be fully populated"
udevadm settle

fg